// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnR-17z5TzBNmfQ4LdHkT0cvOo7LP5pAo',
    appId: '1:620232621907:web:d7f4a01a16554be3e4aba6',
    messagingSenderId: '620232621907',
    projectId: 'instaclone-96d22',
    authDomain: 'instaclone-96d22.firebaseapp.com',
    storageBucket: 'instaclone-96d22.appspot.com',
    measurementId: 'G-BGVW3QHJX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC09vvoeKQV08nVlUcGlWfoYfUUL1cUO_I',
    appId: '1:620232621907:android:ec2d32d42a9ea010e4aba6',
    messagingSenderId: '620232621907',
    projectId: 'instaclone-96d22',
    storageBucket: 'instaclone-96d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM2474yIuf8v2aSO5s2sUYJ0CkGRX3EK4',
    appId: '1:620232621907:ios:0ebabb34a699b354e4aba6',
    messagingSenderId: '620232621907',
    projectId: 'instaclone-96d22',
    storageBucket: 'instaclone-96d22.appspot.com',
    iosClientId: '620232621907-nh8pb7vvnrtqb70l3ph1lufc70m96n4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.socilamediaOneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM2474yIuf8v2aSO5s2sUYJ0CkGRX3EK4',
    appId: '1:620232621907:ios:0ebabb34a699b354e4aba6',
    messagingSenderId: '620232621907',
    projectId: 'instaclone-96d22',
    storageBucket: 'instaclone-96d22.appspot.com',
    iosClientId: '620232621907-nh8pb7vvnrtqb70l3ph1lufc70m96n4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.socilamediaOneFlutter',
  );
}
